name: Deploy Documentation to Wiki

on:
  push:
    branches:
      - main  # Triggers on any push to main
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy-to-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          path: source

      - name: Checkout wiki
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: source/package-lock.json

      - name: Install dependencies
        working-directory: source
        run: npm ci

      - name: Generate documentation
        working-directory: source
        run: npm run docs  # Ensure this script exists in your package.json

      - name: Copy documentation to wiki
        run: |
          # Remove old docs if they exist
          rm -rf wiki/docs
          # Copy new docs
          cp -R source/docs wiki/docs

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        working-directory: wiki
        run: |
          git add .
          git diff --staged --quiet || {
            git commit -m "docs: update documentation from main branch commit ${{ github.sha }}"
            git push
          }