name: Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js with caching
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Generate documentation
      - name: Generate documentation
        run: npm run docs

      # Step 5: Upload documentation artifact
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./docs

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Download documentation artifact
      - name: Download documentation artifact
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: ./docs

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
