name: Deploy Documentation to Wiki

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Generate documentation
        run: npm run docs  # Assumes `docs` folder is generated

      - name: Deploy to GitHub Wiki
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Clone the Wiki repository using the verified URL
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_TOKEN }}/Snapper.wiki.git || { echo "Failed to clone Wiki repository"; exit 1; }

          # Copy generated documentation to the Wiki repository
          rm -rf .wiki/docs
          cp -R docs .wiki/docs

          # Commit and push changes to the Wiki
          cd .wiki
          git add docs
          git commit -m "Update documentation" || echo "Nothing to commit"
          git push || { echo "Failed to push to Wiki repository"; exit 1; }
