name: Deploy Docusaurus Documentation

on:
  push:
    branches:
      - gh-pages-release  # Replace with your target branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Use the correct node version
          cache: npm

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Generate Typedoc Documentation (from `npm run docs`)
      - name: Generate Typedoc Documentation
        run: npm run docs

      # Step 5: Install Docusaurus manually (without `create-docusaurus`)
      - name: Install Docusaurus
        run: |
          npm install @docusaurus/core @docusaurus/preset-classic


      # Step 7: Build the Docusaurus site
      - name: Build Documentation
        run: npm run build
        working-directory: docusaurus-site

      # Step 8: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: docusaurus-site/build
          publish_branch: gh-pages
