name: Deploy Docusaurus Documentation

on:
  push:
    branches:
      - gh-pages-release  # Trigger on pushes to this branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm

      # Prepare Docusaurus project
      - name: Prepare Docusaurus Project
        run: |
          mkdir -p docusaurus-site/docs
          mkdir -p docusaurus-site/src/css

      # Create Docusaurus Configuration with Dependencies and Scripts
      - name: Create Docusaurus Configuration
        working-directory: docusaurus-site
        run: |
          # Create package.json
          cat > package.json << 'EOL'
          {
            "name": "docs",
            "version": "0.0.0",
            "private": true,
            "scripts": {
              "docusaurus": "docusaurus",
              "start": "docusaurus start",
              "build": "docusaurus build",
              "swizzle": "docusaurus swizzle",
              "deploy": "docusaurus deploy",
              "clear": "docusaurus clear",
              "serve": "docusaurus serve",
              "write-translations": "docusaurus write-translations",
              "write-heading-ids": "docusaurus write-heading-ids"
            },
            "dependencies": {
              "@docusaurus/core": "2.0.0-beta.6",
              "@docusaurus/preset-classic": "2.0.0-beta.6",
              "@mdx-js/react": "^1.6.21",
              "@svgr/webpack": "^5.5.0",
              "clsx": "^1.1.1",
              "file-loader": "^6.2.0",
              "prism-react-renderer": "^1.2.1",
              "react": "^17.0.1",
              "react-dom": "^17.0.1",
              "url-loader": "^4.1.1"
            },
            "browserslist": {
              "production": [
                ">0.5%",
                "not dead",
                "not op_mini all"
              ],
              "development": [
                "last 1 chrome version",
                "last 1 firefox version",
                "last 1 safari version"
              ]
            }
          }
          EOL

          # Create docusaurus.config.js
          cat > docusaurus.config.js << 'EOL'
          const lightCodeTheme = require('prism-react-renderer/themes/github');
          const darkCodeTheme = require('prism-react-renderer/themes/dracula');

          module.exports = {
            title: 'Snapper',
            tagline: 'Snapper Documentation',
            url: 'https://asifqatar.github.io',
            baseUrl: '/Snapper/',
            trailingSlash: false,
            onBrokenLinks: 'warn',
            onBrokenMarkdownLinks: 'warn',
            favicon: 'https://avatars.githubusercontent.com/u/105142204?s=48&v=4',
            organizationName: 'asifqatar',
            projectName: 'Snapper',
            presets: [
              [
                '@docusaurus/preset-classic',
                {
                  docs: {
                    sidebarPath: require.resolve('./sidebars.js'),
                    routeBasePath: '/',
                    editUrl: 'https://github.com/asifqatar/Snapper/blob/main/',
                  },
                  blog: {
                    showReadingTime: true,
                    editUrl: 'https://github.com/asifqatar/Snapper/edit/main/blog/',
                  },
                  theme: {
                    customCss: require.resolve('./src/css/custom.css'),
                  },
                },
              ],
            ],
            themeConfig: {
              navbar: {
                title: 'Snapper',
                logo: {
                  alt: 'Snapper Logo',
                  src: 'https://avatars.githubusercontent.com/u/105142204?s=200&v=4',
                },
                items: [
                  {
                    type: 'doc',
                    docId: 'intro',
                    position: 'left',
                    label: 'Docs',
                  },
                ],
              },
              prism: {
                theme: lightCodeTheme,
                darkTheme: darkCodeTheme,
              },
            },
          };
          EOL

          # Create custom CSS
          echo "/* Custom CSS */" > src/css/custom.css

          # Create intro documentation
          echo "# Introduction to Snapper" > docs/intro.md
      
      # Install Dependencies
      - name: Install Docusaurus Dependencies
        working-directory: docusaurus-site
        run: npm install
        
      # Generate API Documentation using TypeDoc
      - name: Generate API Documentation with TypeDoc
        run: npm run docs  # Runs TypeDoc and generates API docs in the root docs/API folder
        
      - name: Copy API Docs to Docusaurus
        run: |
          if [ -d docs/API ]; then
            cp -r docs/API docusaurus-site/docs/API
          else
            echo "API documentation not found. Skipping copy step."
          fi

      # Build Docusaurus site
      - name: Build Docusaurus Documentation
        working-directory: docusaurus-site
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: docusaurus-site/build
          publish_branch: gh-pages
