name: Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Generate API Documentation with TypeDoc
        run: npm run docs

      - name: Prepare Docusaurus Project
        run: |
          mkdir -p docusaurus-site/docs
          mkdir -p docusaurus-site/src/css

      - name: Create Docusaurus Configuration
        working-directory: docusaurus-site
        run: |
          cat > package.json << 'EOL'
          {
            "name": "snapper-docs",
            "version": "1.0.0",
            "private": true,
            "scripts": {
              "start": "docusaurus start",
              "build": "docusaurus build"
            },
            "dependencies": {
              "@docusaurus/core": "^3.6.3",
              "@docusaurus/preset-classic": "^3.6.3"
            }
          }
          EOL

      - name: Install Docusaurus
        working-directory: docusaurus-site
        run: npm install

      - name: Create Docusaurus Config File
        working-directory: docusaurus-site
        run: |
          cat > docusaurus.config.js << 'EOL'
          module.exports = {
            title: 'Snapper Docs',
            tagline: 'Documentation for Snapper',
            url: 'https://sayfer-io.github.io',
            baseUrl: '/Snapper/',
            onBrokenLinks: 'throw',
            onBrokenMarkdownLinks: 'warn',
            favicon: 'img/favicon.ico',
            organizationName: 'sayfer-io',
            projectName: 'Snapper',
            presets: [
              [
                '@docusaurus/preset-classic',
                {
                  docs: {
                    sidebarPath: require.resolve('./sidebars.js'),
                  },
                  theme: {
                    customCss: require.resolve('./src/css/custom.css'),
                  },
                },
              ],
            ],
          };
          EOL

      - name: Create custom CSS
        working-directory: docusaurus-site/src/css
        run: echo "/* Custom CSS */" > custom.css

      - name: Copy API Docs to Docusaurus
        run: cp -r docs/API docusaurus-site/docs/API

      - name: Run Cleanup Script
        run: |
          cat > cleanup.js << 'EOL'
          const fs = require('fs');
          const path = require('path');
          EOL
          node cleanup.js

      - name: Remove Unnecessary Pages
        run: rm -f docusaurus-site/docs/intro.md

      - name: Build Docusaurus Documentation
        working-directory: docusaurus-site
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: documentation-build
          path: docusaurus-site/build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: documentation-build
          path: build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: build
          publish_branch: gh-pages
