name: Deploy Docusaurus Documentation

on:
  push:
    branches:
      - gh-pages-release  # Trigger on pushes to this branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm
      
      # Install dependencies for TypeDoc
      - name: Install Root Project Dependencies
        run: npm install

      # Generate API Documentation using TypeDoc
      - name: Generate API Documentation with TypeDoc
        run: npm run docs  # Runs TypeDoc and generates API docs in the root docs/API folder
      
      # Prepare Docusaurus project
      - name: Prepare Docusaurus Project
        run: |
          mkdir -p docusaurus-site/docs
          mkdir -p docusaurus-site/src/css
      
      # Create Docusaurus Configuration
      - name: Create Docusaurus Configuration
        working-directory: docusaurus-site
        run: |
          # Create package.json
          cat > package.json << 'EOL'
          {
            "name": "snapper-docs",
            "version": "1.0.0",
            "private": true,
            "scripts": {
              "start": "docusaurus start",
              "build": "docusaurus build"
            }
          }
          EOL
          # Create docusaurus.config.js
          cat > docusaurus.config.js << 'EOL'
          const { themes } = require('prism-react-renderer');
          module.exports = {
            title: 'Snapper',
            tagline: 'Snapper Documentation',
            url: 'https://asifqatar.github.io',
            baseUrl: '/Snapper/',
            trailingSlash: false,
            onBrokenLinks: 'warn',
            onBrokenMarkdownLinks: 'warn',
            favicon: 'https://avatars.githubusercontent.com/u/105142204?s=48&v=4',
            organizationName: 'asifqatar',
            projectName: 'Snapper',
            deploymentBranch: 'gh-pages',
            presets: [
              [
                '@docusaurus/preset-classic',
                {
                  docs: {
                    sidebarPath: require.resolve('./sidebars.js'),
                    routeBasePath: '/',
                    editUrl: 'https://github.com/asifqatar/Snapper/blob/main/',
                  },
                  blog: {
                    showReadingTime: true,
                    editUrl: 'https://github.com/asifqatar/Snapper/edit/main/blog/',
                  },
                  theme: {
                    customCss: require.resolve('./src/css/custom.css'),
                  },
                },
              ],
            ],
            themeConfig: {
              navbar: {
                title: 'Snapper',
                logo: {
                  alt: 'Snapper Logo',
                  src: 'https://avatars.githubusercontent.com/u/105142204?s=200&v=4',
                },
                items: [
                  {
                    type: 'doc',
                    docId: 'intro',
                    position: 'left',
                    label: 'Docs',
                  },
                ],
              },
              prism: {
                theme: themes.github,
                darkTheme: themes.dracula,
              },
            },
          };
          EOL
          # Create custom CSS
          echo "/* Custom CSS */" > src/css/custom.css
          # Create intro documentation
          echo "# Introduction to Snapper" > docs/intro.md

      # Create sidebars.js
      - name: Create sidebars.js
        working-directory: docusaurus-site
        run: |
          cat > sidebars.js << 'EOL'
          module.exports = {
            // By default, Docusaurus generates a sidebar from the docs folder structure
            tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
          };
          EOL
      
      # Install Docusaurus Dependencies
      - name: Install Docusaurus Dependencies
        working-directory: docusaurus-site
        run: |
          npm install @docusaurus/core @docusaurus/preset-classic @docusaurus/theme-classic prism-react-renderer
      
      # Copy API Docs into Docusaurus docs folder
      - name: Copy API Docs to Docusaurus
        run: cp -r docs/API docusaurus-site/docs/API

      # Build Docusaurus site
      - name: Build Docusaurus Documentation
        working-directory: docusaurus-site
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: docusaurus-site/build
          publish_branch: gh-pages
