name: Deploy Docusaurus Documentation

on:
  push:
    branches:
      - gh-pages-release  # Replace with your target branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Use the correct node version
          cache: npm

      # Step 3: Install Docusaurus dependencies
      - name: Install Docusaurus Dependencies
        working-directory: docusaurus-site  # Specify the Docusaurus directory
        run: |
          npm init -y  # Create package.json if not exists
          npm install @docusaurus/core @docusaurus/preset-classic

      # Step 4: Build Docusaurus Site
      - name: Build Docusaurus Documentation
        working-directory: docusaurus-site
        run: npx docusaurus build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docusaurus-site/build
          publish_branch: gh-pages