name: Documentation

on:
  push:
    branches:
      - gh-pages-release # Or any branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Ensure the node version matches your project's requirements
          cache: npm

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Generate Typedoc Documentation (from `npm run docs`)
      - name: Generate Typedoc Documentation
        run: npm run docs

      # Step 5: Install Docusaurus
      - name: Install Docusaurus
        run: |
          npx create-docusaurus@latest docusaurus-site classic --skip-install
          cd docusaurus-site
          npm install

      # Step 6: Move Typedoc Output to Docusaurus
      - name: Move Typedoc Output
        run: |
          mv ./docs docusaurus-site/docs # Move Typedoc output to Docusaurus' docs folder
        working-directory: .

      # Step 7: Build the Docusaurus site
      - name: Build Documentation
        run: npm run build
        working-directory: docusaurus-site

      # Step 8: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: docusaurus-site/build
          publish_branch: gh-pages
