name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      # Checkout the code with full history for semantic-release
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup Node.js environment
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Optional: Build the project (if required for npm package or docs generation)
      - run: npm run build

      # Optional: Run security audit (can be skipped if not necessary)
      - run: npm audit signatures

      # Run semantic-release to publish
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
