name: Build
on:
  push:
    branches: [main, develop, building-ci-cd]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Set SonarCloud URL
        run: |
          echo "SONAR_URL=https://sonarcloud.io/project/overview?id=${{ github.repository_owner }}_${{ github.event.repository.name }}" >> $GITHUB_ENV
      - name: Create custom output
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            fs.writeFileSync(process.env.GITHUB_STEP_SUMMARY, `## SonarCloud Analysis\n[View on SonarCloud](${process.env.SONAR_URL})`);
            core.setOutput('sonar-url', process.env.SONAR_URL);
    outputs:
      sonar-url: ${{ steps.create-custom-output.outputs.sonar-url }}
